# Generated by Django 3.1.1 on 2020-09-17 05:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_auto_20200916_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='articulo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
