# Generated by Django 3.1.1 on 2020-09-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_auto_20200917_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click en el link para leer el blog', max_length=255),
        ),
    ]
